name: C/C++ CI

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd hello && make
    - name: make check
      run: cd hello && make check
    - name: make distcheck
      run: cd hello && make distcheck
